config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :users

  get 'session/create'
  get 'session/destroy'
  get 'session/new'

  root 'orders#user_index'
  get 'current-orders' => 'orders#index'
  get 'past-orders' => 'orders#past_index'

  get 'register' => 'users#new'
  get 'users' => 'users#index'
  get 'edit' => 'users#edit'

  get 'login' => 'session#new'
  post 'login' => 'session#create'
  get 'logout' => 'session#destroy'

  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :users do
    member do
        get :approve
    end
  end

  resources :users do
    member do
        get :change_admin_status
    end
  end

  resources :orders do
    member do
        get :confirm_payment
    end
  end

  resources :orders do
    member do
        get :confirm_delivery
    end
  end

  scope '/hooks', :controller => :hooks do
    post :new_order_callback
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword
  has_many :orders

  before_create :confirmation_token

  field :name, type: String
  field :email, type: String
  field :password_digest, type: String
  field :confirmed, type: Boolean, default: false
  field :confirm_token, type: String
  field :approved, type: Boolean, default: false
  field :admin, type: Boolean, default: false

  has_secure_password
  validates_presence_of :name, :email, :password
  validates :email, :uniqueness => true
  validates :password, :length => {
    :minimum => 6,
    :maximum => 20,
    :too_short => "Passwords must be at least %{count} characters.",
    :too_long => "Passwords must be at most %{count} characters."
  }

  def email_activate
    self.confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  end

  def approve
    self.approved = true
    save!(:validate => false)
  end

  def toggle_admin
    self.admin = !self.admin
    save!(:validate => false)
  end

  private

    def confirmation_token
      if self.confirm_token.blank?
          self.confirm_token = SecureRandom.urlsafe_base64.to_s
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :approve,
                                  :change_admin_status]
  skip_before_filter :require_user, :only => [:create, :new, :confirm_email]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        UsersMailer.registration_confirmation(@user).deliver_now
        format.html { redirect_to @user, notice: 'Success! Confirm your email to continue.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm_email
    user = User.find_by(confirm_token: params[:id])
    if user
      user.email_activate
      flash[:success] = "Your email has been confirmed."
      redirect_to login_url
    else
      flash[:error] = "We couldn't find that user."
      redirect_to root_url
    end
  end

  def approve
    if @user.approve
      flash[:success] = "That user is now approved!"
      redirect_to users_url
    else
      flash[:error] = "That didn't work!"
      redirect_to users_url
    end
  end

  def change_admin_status
    if @user.toggle_admin
      flash[:success] = "That user's admin change was successful."
      redirect_to users_url
    else
      flash[:error] = "That didn't work!"
      redirect_to users_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="row">
      <div class="col-md-2 col-md-offset-5">
        <%= f.label :name %><br>
        <%= f.text_field :name, {class: "form-control"} %>
      </div>
    </div><br>
    <div class="row">
      <div class="col-md-2 col-md-offset-5">
        <%= f.label :email %><br>
        <%= f.text_field :email, {class: "form-control"} %>
      </div>
    </div><br>
    <div class="row">
      <div class="col-md-2 col-md-offset-5">
        <%= f.label :password %><br>
        <%= f.password_field :password, {class: "form-control"} %>
      </div>
    </div><br>
    <div class="actions">
      <%= f.submit "Submit", :class => "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="text-center">
  <h1>Edit User</h1>

  <%= render 'form' %>

  <%= link_to 'Back', users_path %>
</div>

app/views/users/index.html.erb
<div class="text-center">
  <% if @current_user.admin %>
    <% flash.each do |key, value| %>
      <p class="alert alert-<%= key %>"><%= value %></p>
    <% end %>
    <p id="notice"><%= notice %></p>

    <h1>Users</h1>

    <table class="table table-striped">
      <thead>
        <tr>
          <th class="text-center">Name</th>
          <th class="text-center">Email</th>
          <th class="text-center">Admin</th>
          <th class="text-center">Status</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= link_to (user.admin ? "Yes" : "No"), change_admin_status_user_path(user) %></td>
            <td><%= link_to (user.approved ? "Approved" : "Pending"), approve_user_path(user) %></td>
            <td><%= link_to "<i class=\"fa fa-pencil\"></i>".html_safe, edit_user_path(user) %></td>
            <td><%= link_to "<i class=\"fa fa-trash\"></i>".html_safe, user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <br><br><p>You need to be an admin to view users!</p>
  <% end %>

  <br>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Register</h1>

  <%= render 'form' %>

  <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<div class="text-center">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Name:</strong>
      <%= @user.name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <p>
      <strong>Admin:</strong>
      <%= @user.admin %>
    </p>

    <%= link_to 'Edit', edit_user_path(@user) %> |
    <%= link_to 'Back', users_path %>
</div>