config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :users

  get 'session/create'
  get 'session/destroy'
  get 'session/new'

  root 'orders#user_index'
  get 'current-orders' => 'orders#index'
  get 'past-orders' => 'orders#past_index'

  get 'register' => 'users#new'
  get 'users' => 'users#index'
  get 'edit' => 'users#edit'

  get 'login' => 'session#new'
  post 'login' => 'session#create'
  get 'logout' => 'session#destroy'

  resources :users do
    member do
      get :confirm_email
    end
  end

  resources :users do
    member do
        get :approve
    end
  end

  resources :users do
    member do
        get :change_admin_status
    end
  end

  resources :orders do
    member do
        get :confirm_payment
    end
  end

  resources :orders do
    member do
        get :confirm_delivery
    end
  end

  scope '/hooks', :controller => :hooks do
    post :new_order_callback
  end

end

app/models/order.rb
class Order
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  belongs_to :user

  field :buyer_name, type: String
  field :buyer_email, type: String
  field :recipient_name, type: String
  field :recipient_address, type: String
  field :date, type: Date
  field :items, type: String
  field :message, type: String
  field :anonymous, type: Boolean
  field :venmo_username, type: String
  field :paid, type: Boolean, default: false
  field :delivered, type: Boolean, default: false
  field :created_at, type: DateTime, default: ->{ Time.now }
  field :delivered_at, type: DateTime

  def confirm_payment
    self.paid = true
    save!(:validate => false)
  end

  def confirm_delivery
    self.delivered = true
    self.delivered_at = Time.now
    save!(:validate => false)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy,
                                   :confirm_payment, :confirm_delivery]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where(:delivered => false).paginate(:page => params[:page],
                                                        :per_page => 20)
  end

  def past_index
    @orders = Order.where(:delivered => true).paginate(:page => params[:page],
                                                      :per_page => 20)
  end

  # GET /my_orders
  def user_index
    @current_orders = @current_user.orders.where(:delivered => false).paginate(
                                                        :page => params[:page],
                                                        :per_page => 10)
    @past_orders = @current_user.orders.where(:delivered => true).paginate(
                                                        :page => params[:page],
                                                        :per_page => 10)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @users = User.all
  end

  # GET /orders/1/edit
  def edit
    @users = User.all
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @user = User.find(params[:user_id][:id])
    @user.orders << @order

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    @user = User.find(params[:user_id][:id])
    @user.orders << @order
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm_payment
    if @order.confirm_payment
      OrdersMailer.payment_confirmation(@order).deliver_now
      flash[:success] = "Payment confirmation sent!"
      redirect_to root_url
    else
      flash[:error] = "That didn't work!"
      redirect_to root_url
    end
  end

  def confirm_delivery
    if @order.confirm_delivery
      OrdersMailer.delivery_confirmation(@order).deliver_now
      flash[:success] = "Delivery confirmation sent!"
      redirect_to root_url
    else
      flash[:error] = "That didn't work!"
      redirect_to root_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:buyer_name, :buyer_email, :recipient_name,
                                    :recipient_address, :date, :number,
                                    :items, :message, :anonymous,
                                    :venmo_username)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="row">
      <div class="col-md-2 col-md-offset-4">
        <%= f.label :buyer_name, "Buyer Name" %><br>
        <%= f.text_field :buyer_name, {class: "form-control"} %>
      </div>
      <div class="col-md-2">
        <%= f.label :buyer_email, "Buyer Email" %><br>
        <%= f.text_field :buyer_email, {class: "form-control"} %>
      </div>
    </div><br>
    <div class="row">
      <div class="col-md-2 col-md-offset-4">
        <%= f.label :recipient_name, "Recipient Name" %><br>
        <%= f.text_field :recipient_name, {class: "form-control"} %>
      </div>
      <div class="col-md-2">
        <%= f.label :recipient_address, "Recipient Address" %><br>
        <%= f.text_field :recipient_address, {class: "form-control"} %>
      </div>
    </div><br>
    <div class="row">
      <%= f.label :date %><br>
      <%= f.date_select :date, {}, {class: "form-control date-select"} %>
    </div><br>
    <div class="row">
      <div class="col-md-2 col-md-offset-4">
        <%= f.label :items %><br>
        <%= f.text_area :items, {class: "form-control", rows: "4"} %>
      </div>
      <div class="col-md-2">
        <%= f.label :message %><br>
        <%= f.text_area :message, {class: "form-control", rows: "4"} %>
      </div>
    </div><br>
    <div class="row">
      <div class="col-md-2 col-md-offset-4">
        <%= f.label :anonymous %><br>
        <%= f.check_box :anonymous %>
      </div>
      <div class="col-md-2">
        <%= f.label :venmo_username, "Venmo Username" %><br>
        <%= f.text_field :venmo_username, {class: "form-control"} %>
      </div>
    </div><br>
    <div class="row">
      <div class="col-md-2 col-md-offset-5">
        <%= f.label :deliverer, "Deliverer" %><br>
        <%= collection_select :user_id, :id, @users, :id, :name, {}, {class: "form-control"} %>
      </div>
    </div><br>
    <div class="actions">
      <%= f.submit "Submit", :class => "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/orders/edit.html.erb
<div class="text-center">
  <h1>Edit Order</h1>

  <%= render 'form' %>
</div>

app/views/orders/index.html.erb
<div class="text-center">
  <% flash.each do |key, value| %>
    <p class="alert alert-<%= key %>"><%= value %></p>
  <% end %>

  <h1>Current Orders</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
        <th class="text-center">Buyer Name</th>
        <th class="text-center">Buyer Email</th>
        <th class="text-center">Recipient Name</th>
        <th class="text-center">Recipient Address</th>
        <th class="text-center">Date</th>
        <th class="text-center">Venmo Username</th>
        <th class="text-center">Deliverer</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td>
            <% if !order.paid %>
              <%= link_to "<i class=\"fa fa-credit-card-alt\"></i>".html_safe, confirm_payment_order_path(order) %>
            <% elsif !order.delivered %>
              <%= link_to "<i class=\"fa fa-paper-plane\"></i>".html_safe, confirm_delivery_order_path(order) %>
            <% end %>
          </td>
          <td><%= order.buyer_name %></td>
          <td><%= order.buyer_email %></td>
          <td><%= order.recipient_name %></td>
          <td><%= order.recipient_address %></td>
          <td><%= order.date %></td>
          <td><%= order.venmo_username %></td>
          <td>
            <% if order.user %>
              <%= order.user.name %>
            <% end %>
          </td>
          <td><%= link_to "<i class=\"fa fa-eye\"></i>".html_safe, order_path(order) %></td>
          <td><%= link_to "<i class=\"fa fa-pencil\"></i>".html_safe, edit_order_path(order) %></td>
          <td><%= link_to "<i class=\"fa fa-trash\"></i>".html_safe, order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @orders %>

  <br>

  <%= link_to 'New Order', new_order_path %>
</div>

app/views/orders/new.html.erb
<div class="text-center">
  <h1>New Order</h1>

  <%= render 'form' %>
</div>

app/views/orders/past_index.html.erb
<div class="text-center">
  <% flash.each do |key, value| %>
    <p class="alert alert-<%= key %>"><%= value %></p>
  <% end %>

  <h1>Past Orders</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th class="text-center">Buyer Name</th>
        <th class="text-center">Buyer Email</th>
        <th class="text-center">Recipient Name</th>
        <th class="text-center">Recipient Address</th>
        <th class="text-center">Date</th>
        <th class="text-center">Venmo Username</th>
        <th class="text-center">Deliverer</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.buyer_name %></td>
          <td><%= order.buyer_email %></td>
          <td><%= order.recipient_name %></td>
          <td><%= order.recipient_address %></td>
          <td><%= order.date %></td>
          <td><%= order.venmo_username %></td>
          <td>
            <% if order.user %>
              <%= order.user.name %>
            <% end %>
          </td>
          <td><%= link_to "<i class=\"fa fa-eye\"></i>".html_safe, order_path(order) %></td>
          <td><%= link_to "<i class=\"fa fa-pencil\"></i>".html_safe, edit_order_path(order) %></td>
          <td><%= link_to "<i class=\"fa fa-trash\"></i>".html_safe, order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @orders %>

  <br>
</div>

app/views/orders/show.html.erb
<div class="text-center">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Buyer Name:</strong>
    <%= @order.buyer_name %>
  </p>

  <p>
    <strong>Buyer Email:</strong>
    <%= @order.buyer_email %>
  </p>

  <p>
    <strong>Recipient Name:</strong>
    <%= @order.recipient_name %>
  </p>

  <p>
    <strong>Recipient Address:</strong>
    <%= @order.recipient_address %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= @order.date %>
  </p>

  <p>
    <strong>Items:</strong>
    <%= @order.items.html_safe %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= @order.message %>
  </p>

  <p>
    <strong>Anonymous:</strong>
    <% if @order.anonymous %>
      Yes
    <% else %>
      No
    <% end %>
  </p>

  <p>
    <strong>Venmo Username:</strong>
    <%= @order.venmo_username %>
  </p>

  <%= link_to 'Edit', edit_order_path(@order) %> |
  <%= link_to 'Back', orders_path %>
</div>

app/views/orders/user_index.html.erb
<div class="text-center">
  <p id="notice"><%= notice %></p>

  <h1>My Orders</h1>

  <h3>Current Orders</h3>

  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
        <th class="text-center">Buyer Name</th>
        <th class="text-center">Buyer Email</th>
        <th class="text-center">Recipient Name</th>
        <th class="text-center">Recipient Address</th>
        <th class="text-center">Date</th>
        <th class="text-center">Venmo Username</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @current_orders.each do |order| %>
        <tr>
          <td>
            <% if !order.paid %>
              <%= link_to "<i class=\"fa fa-credit-card-alt\"></i>".html_safe, confirm_payment_order_path(order) %>
            <% elsif !order.delivered %>
              <%= link_to "<i class=\"fa fa-paper-plane\"></i>".html_safe, confirm_delivery_order_path(order) %>
            <% end %>
          </td>
          <td><%= order.buyer_name %></td>
          <td><%= order.buyer_email %></td>
          <td><%= order.recipient_name %></td>
          <td><%= order.recipient_address %></td>
          <td><%= order.date %></td>
          <td><%= order.venmo_username %></td>
          <td><%= link_to "<i class=\"fa fa-eye\"></i>".html_safe, order_path(order) %></td>
          <td><%= link_to "<i class=\"fa fa-pencil\"></i>".html_safe, edit_order_path(order) %></td>
          <td><%= link_to "<i class=\"fa fa-trash\"></i>".html_safe, order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @current_orders %>
  <br><br><br><br><br>

  <h3>Past Orders</h3>

    <table class="table table-striped">
    <thead>
      <tr>
        <th class="text-center">Buyer Name</th>
        <th class="text-center">Buyer Email</th>
        <th class="text-center">Recipient Name</th>
        <th class="text-center">Recipient Address</th>
        <th class="text-center">Date</th>
        <th class="text-center">Venmo Username</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @past_orders.each do |order| %>
        <tr>
          <td><%= order.buyer_name %></td>
          <td><%= order.buyer_email %></td>
          <td><%= order.recipient_name %></td>
          <td><%= order.recipient_address %></td>
          <td><%= order.date %></td>
          <td><%= order.venmo_username %></td>
          <td><%= link_to "<i class=\"fa fa-eye\"></i>".html_safe, order_path(order) %></td>
          <td><%= link_to "<i class=\"fa fa-pencil\"></i>".html_safe, edit_order_path(order) %></td>
          <td><%= link_to "<i class=\"fa fa-trash\"></i>".html_safe, order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @past_orders %>

  <br>
</div>